/* eslint-disable import/no-commonjs */

module.exports = {
  rules: {
    // https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md
    'order/order': [
      [
        'dollar-variables',
        'at-variables',
        'custom-properties',
        'at-rules',
        'less-mixins',
        'declarations',
        'rules',
      ],
      {
        unspecified: 'bottom',
        disableFix: false,
      },
    ],

    // https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-order/README.md
    'order/properties-order': [
      [
        {
          properties: [
            'position',
            'inset',
            'inset-block',
            'inset-inline',
            'inset-block-start',
            'inset-block-end',
            'inset-inline-start',
            'inset-inline-end',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Positioning',
        },

        {
          properties: ['box-sizing', 'display'],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Display mode',
        },

        {
          properties: [
            'flex',
            'flex-basis',
            'flex-direction',
            'flex-flow',
            'flex-grow',
            'flex-shrink',
            'flex-wrap',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Flexbox',
        },

        {
          properties: [
            'grid',
            'grid-area',
            'grid-template',
            'grid-template-areas',
            'grid-template-rows',
            'grid-template-columns',
            'grid-row',
            'grid-row-start',
            'grid-row-end',
            'grid-column',
            'grid-column-start',
            'grid-column-end',
            'grid-auto-rows',
            'grid-auto-columns',
            'grid-auto-flow',
            'grid-gap',
            'grid-row-gap',
            'grid-column-gap',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Grid',
        },

        {
          properties: ['gap', 'row-gap', 'column-gap'],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Gap',
        },

        {
          properties: [
            'place-content',
            'place-items',
            'place-self',
            'align-content',
            'align-items',
            'align-self',
            'justify-content',
            'justify-items',
            'justify-self',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Layout alignment',
        },

        {
          properties: ['order'],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Order',
        },
        {
          properties: [
            'float',
            'inline-size',
            'min-inline-size',
            'max-inline-size',
            'block-size',
            'min-block-size',
            'max-block-size',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'padding',
            'padding-inline',
            'padding-inline-start',
            'padding-inline-end',
            'padding-block',
            'padding-block-start',
            'padding-block-end',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'margin',
            'margin-inline',
            'margin-inline-start',
            'margin-inline-end',
            'margin-block',
            'margin-block-start',
            'margin-block-end',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'overflow',
            'overflow-inline',
            'overflow-block',
            'overflow-x',
            'overflow-y',
            'overscroll-behavior',
            'overscroll-behavior-inline',
            'overscroll-behavior-block',
            'overscroll-behavior-x',
            'overscroll-behavior-y',
            'clip',
            'clip-path',
            'clear',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Box model',
        },

        {
          properties: [
            'font',
            'font-family',
            'font-size',
            'font-style',
            'font-weight',
            'font-feature-settings',
            'font-kerning',
            'font-variant',
            'font-variant-ligatures',
            'font-variant-caps',
            'font-variant-alternates',
            'font-variant-numeric',
            'font-variant-east-asian',
            'font-variant-position',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'font-emphasize-position',
            'font-emphasize-style',
            'font-smooth',
            'hyphens',
            'line-height',
            'color',
            'text-align',
            'text-align-last',
            'text-emphasis',
            'text-emphasis-color',
            'text-emphasis-style',
            'text-emphasis-position',
            'text-decoration',
            'text-decoration-line',
            'text-decoration-thickness',
            'text-decoration-style',
            'text-decoration-color',
            'text-underline-position',
            'text-underline-offset',
            'text-indent',
            'text-justify',
            'text-outline',
            'text-overflow',
            'text-overflow-ellipsis',
            'text-overflow-mode',
            'text-shadow',
            'text-transform',
            'text-wrap',
            'letter-spacing',
            'word-break',
            'word-spacing',
            'overflow-wrap',
            'tab-size',
            'white-space',
            'vertical-align',
            'list-style',
            'list-style-position',
            'list-style-type',
            'list-style-image',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Typography',
        },

        {
          properties: [
            'pointer-events',
            'touch-action',
            'cursor',
            'visibility',
            'zoom',
            'table-layout',
            'empty-cells',
            'caption-side',
            'border-spacing',
            'border-collapse',
            'content',
            'quotes',
            'counter-reset',
            'counter-increment',
            'resize',
            'user-select',
            'nav-index',
            'nav-up',
            'nav-right',
            'nav-down',
            'nav-left',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Accessibility & Interactions',
        },

        {
          properties: [
            'background',
            'background-color',
            'background-image',
            'filter',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',
            'background-blend-mode',
            'isolation',
            'border',
            'border-inline',
            'border-inline-start',
            'border-inline-end',
            'border-block',
            'border-block-start',
            'border-block-end',
            'border-width',
            'border-inline-width',
            'border-inline-start-width',
            'border-inline-end-width',
            'border-block-width',
            'border-block-start-width',
            'border-block-end-width',
            'border-style',
            'border-inline-style',
            'border-inline-start-style',
            'border-inline-end-style',
            'border-block-style',
            'border-block-start-style',
            'border-block-end-style',
            'border-color',
            'border-inline-color',
            'border-inline-start-color',
            'border-inline-end-color',
            'border-block-color',
            'border-block-start-color',
            'border-block-end-color',
            'border-top',
            'border-top-width',
            'border-top-style',
            'border-top-color',
            'border-right',
            'border-right-width',
            'border-right-style',
            'border-right-color',
            'border-bottom',
            'border-bottom-width',
            'border-bottom-style',
            'border-bottom-color',
            'border-left',
            'border-left-width',
            'border-left-style',
            'border-left-color',
            'border-radius',
            'border-start-start-radius',
            'border-start-end-radius',
            'border-end-start-radius',
            'border-end-end-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
            'border-image',
            'border-image-source',
            'border-image-slice',
            'border-image-width',
            'border-image-outset',
            'border-image-repeat',
            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',
            'box-shadow',
            'mix-blend-mode',
            'opacity',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Background & Borders',
        },

        {
          properties: [
            'alignment-baseline',
            'baseline-shift',
            'dominant-baseline',
            'text-anchor',
            'word-spacing',
            'writing-mode',

            'fill',
            'fill-opacity',
            'fill-rule',
            'stroke',
            'stroke-dasharray',
            'stroke-dashoffset',
            'stroke-linecap',
            'stroke-linejoin',
            'stroke-miterlimit',
            'stroke-opacity',
            'stroke-width',

            'color-interpolation',
            'color-interpolation-filters',
            'color-profile',
            'color-rendering',
            'flood-color',
            'flood-opacity',
            'image-rendering',
            'lighting-color',
            'marker-start',
            'marker-mid',
            'marker-end',
            'mask',
            'shape-rendering',
            'stop-color',
            'stop-opacity',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'SVG Presentation Attributes',
        },

        {
          properties: [
            'transition',
            'transition-delay',
            'transition-timing-function',
            'transition-duration',
            'transition-property',
            'transform',
            'transform-origin',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
          ],
          emptyLineBefore: 'always',
          noEmptyLineBetween: true,
          groupName: 'Transitions & Animation',
        },
      ],
      {
        unspecified: 'bottom',
        emptyLineBeforeUnspecified: 'always',
        emptyLineMinimumPropertyThreshold: 1,
        disableFix: false,
      },
    ],

    // https://github.com/hudochenkov/stylelint-order/blob/master/rules/properties-alphabetical-order/README.md
    // 'order/properties-alphabetical-order': [true, { disableFix: false }],
  },
}
